### ISSUE TITLE
Accurate Docker instructions?

### ISSUE THREAD

**Issue by heyitsguay** [ximinng/SVGDreamer#28]
Hey, would it be possible to get accurate instructions for running this using the Docker container you provide? Here is my experience (On Ubuntu 22.04 with a 3090Ti):

- Modify the suggested docker command to map the project directory to the workspace:
```bash
docker run --name svgdreamer --gpus all -it --ipc=host -v $(pwd):/workspace ximingxing/svgrender:v1 /bin/bash
```

- Eventually figure out that there is an `svgrender` conda environment (not documented). Activate it. 
```bash
source /opt/conda/etc/profile.d/conda.sh
conda activate svgrender
```

Try to run a sample:
```python
python svgdreamer.py x=iconography skip_sive=False "prompt='an image of Batman. full body action pose, complete detailed body. white background. empty background, high quality, 4K, ultra realistic'" token_ind=4 x.vpsd.t_schedule='randint' result_path='./logs/batman' multirun=True
```

Get an error about cairosvg not being installed. Install it with `pip install cairosvg`, but the cairo libraries do not appear to be on the system:
```
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': libcairo.so.2: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcairo.so.2'
```

I can try to play whack-a-mole on this stuff for a while, but it seems like something has gone wrong with your Docker image and/or instructions, and the project could benefit from accurate, reproducible instructions for running SVGDreamer through docker.

Thank you!
Matt

**Comment by heyitsguay** [comment]
And in case anyone else runs into this; once the conda env is active:
```bash
pip install cairosvg
apt update
apt install libcairo2-dev
```

At that point, the example worked for me (once i enabled downloading the SD model in the config.yaml file as documented)

**Comment by ximinng** [comment]
Thanks for sharing your experience, Matt! It sounds like there are some missing dependencies and documentation gaps for running SVGDreamer in the provided Docker container. Below, I'll provide accurate, reproducible instructions to get it running smoothly on Ubuntu 22.04 with an NVIDIA GPU.

1. Pull the Docker Image
```
docker pull ximingxing/svgrender:v1
```

2. Run the Docker Container
```
docker run --name svgdreamer --gpus all -it --ipc=host -v $(pwd):/workspace ximingxing/svgrender:v1 /bin/bash
```

3. Activate the Conda Environment
```
source /opt/conda/etc/profile.d/conda.sh
conda activate svgrender
```

4. Install Missing Dependencies
```
pip install cairosvg
apt update
apt install -y libcairo2-dev
```

5. Enable Stable Diffusion Model Download

6. Run SVGDreamer with a Sample Prompt
```
python svgdreamer.py x=iconography skip_sive=False \
  "prompt='an image of Batman. full body action pose, complete detailed body. white background. empty background, high quality, 4K, ultra realistic'" \
  token_ind=4 x.vpsd.t_schedule='randint' \
  result_path='./logs/batman' multirun=True
```

This should now work reproducibly for other users. Thanks again for reporting this, and I hope this helps others facing the same issue!

Let me know if you need any refinements!

**Comment by xiaoyao9184** [comment]
To make the setup reproducible, I built an alternative workflow using a precompiled [diffvg wheel](https://github.com/xiaoyao9184/wheel-diffvg/releases/tag/wheels-f548de3c6bac885eb69bab33c29447fc357c2821).

For this project diffvg wheel is compiled in: `pytorch/pytorch:2.3.1-cuda11.8-cudnn8-devel`
and runs in runtime image: `pytorch/pytorch:2.3.1-cuda11.8-cudnn8-runtime`

This avoids rebuilding diffvg inside the container and eliminates several dependency issues.

Example docker-compose container:

```yaml
services:
  svgdreamer_cli:
    image: xiaoyao9184/svgdreamer:main
    container_name: svgdreamer_cli
    command:
      - x=iconography
      - skip_sive=False
      - "prompt='an image of Batman. full body action pose, complete detailed body. white background. empty background, high quality, 4K, ultra realistic'"
      - token_ind=4
      - "x.vpsd.t_schedule='randint'"
      - "result_path='./logs/batman'"
      - multirun=True
    environment:
      - TORCH_DEVICE=cuda
      - HF_HUB_OFFLINE=true
    volumes:
      - ./../../cache:/root/.cache
      - ./../../logs:/app/logs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]

```

Hope [docker-svgdreamer](https://github.com/xiaoyao9184/docker-svgdreamer) helps others trying to run SVGDreamer in Docker.
